SCREEN 13
DEFINT A-Z
FOR COL = 0 TO 255
   OUT &H3C8, COL
   OUT &H3C9, 0
   OUT &H3C9, 0
   OUT &H3C9, 0
NEXT COL
COL = 1
FOR Y = 0 TO 400
   CIRCLE (160, 100), Y, COL, , , .3
   COL = COL + 1
   IF COL = 256 THEN COL = 1
NEXT Y
'LOCATE 2, 9
'READ TITLE$
'FOR COL = 1 TO 26
'   COLOR COL
'   PRINT MID$(TITLE$, COL, 1);
'NEXT COL
'LOCATE 3, 2
'READ TITLE$
'FOR COL = 1 TO 38
'   COLOR COL
'   PRINT MID$(TITLE$, COL, 1);
'NEXT COL
'LOCATE 24, 16
'READ TITLE$
'FOR COL = 1 TO 12
'   COLOR COL
'   PRINT MID$(TITLE$, COL, 1);
'NEXT COL
COL = 0
DO
   FOR PAL = 0 TO 63 STEP 1
      OUT &H3C8, COL
      OUT &H3C9, 0
      OUT &H3C9, PAL
      OUT &H3C9, PAL
      COL = COL + 1
      IF COL = 256 THEN COL = 1
   NEXT PAL
   FOR PAL = 63 TO 0 STEP -1
      OUT &H3C8, COL
      OUT &H3C9, 0
      OUT &H3C9, PAL
      OUT &H3C9, PAL
      COL = COL + 1
      IF COL = 256 THEN COL = 1
   NEXT PAL
LOOP UNTIL INKEY$ <> ""
SCREEN 0: WIDTH 80
CLS

DATA "WAVE EFFECT SCREEN SAVER", "COPYRIGHT (c)1997 BY ROB VAN DER LINDE", "PRESS A KEY!"

